name: DisenchantmentTotem
version: 1.1
main: com.MaxAkt.disenchantmenttotem.DisenchantmentTotem
api-version: '1.20'
author: MaxAkt
description: A totem that removes enchantments from player tools, armor and items while in its radius.